name: Deploy dev-tools-portal to App Runner

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-central-1
  ECR_REPO: dev-tools-portal

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::506279660142:role/GitHubActions-ECR-Push
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPO:${GITHUB_SHA} .

      - name: Tag & push image to ECR
        run: |
          docker tag $ECR_REPO:${GITHUB_SHA} \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO:${GITHUB_SHA}


          docker push \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO:${GITHUB_SHA}
      - name: Update App Runner service
        run: |
          REGISTRY=${{ steps.login-ecr.outputs.registry }}
          # Tag with latest (mutable) - App Runner should track this
          docker tag $ECR_REPO:${GITHUB_SHA} $REGISTRY/$ECR_REPO:latest
          docker push $REGISTRY/$ECR_REPO:latest
